function writesacout(R,T,L,Q,dz,basename)
% Write out the sac format using  mksac
% François Beauducel (2021). RDSAC and MKSAC: read and write SAC seismic data file (https://github.com/IPGP/sac-matlab), GitHub. Retrieved February 24, 2021.
% Input: R,T,L,Q: array of R,T,L,Q 
%        dz: references structures to get the flag
%% Organize the outputs
    comname = dz.kcmpnm;
    comr = [comname(1:2),'R']; % write out component r
    Rn = strrep(basename,comname,comr);
    comt = [comname(1:2),'T']; % write out component T
    Tn = strrep(basename,comname,comt);
    coml = [comname(1:2),'L']; % write out component L
    Ln = strrep(basename,comname,coml);
    comq = [comname(1:2),'Q']; % write out component Q
    Qn = strrep(basename,comname,comq);
%% Read all the flag from references structures and write out
% R
   mksac(Rn,R,now,'DELTA',dz.delta,'T0',dz.t0,...
       'STLA',dz.stla,'STLO',dz.stlo,'STEL',dz.stel,'STDP',dz.stdp,...
       'EVLA',dz.evla,'EVLO',dz.evlo,'EVEL',dz.evel,'EVDP',dz.evdp,'MAG',dz.mag,...
       'GCARC',dz.gcarc,'NZYEAR',dz.nzyear,'NZJDAY',dz.nzjday,...
       'NZHOUR',dz.nzhour,'NZMIN',dz.nzmin,'NZSEC',dz.nzsec,'NZMSEC',dz.nzmsec,...
       'NVHDR',dz.nvhdr,'KSTNM',dz.kstnm,'KCMPNM',comr)
% T
   mksac(Tn,T,now,'DELTA',dz.delta,'T0',dz.t0,...
       'STLA',dz.stla,'STLO',dz.stlo,'STEL',dz.stel,'STDP',dz.stdp,...
       'EVLA',dz.evla,'EVLO',dz.evlo,'EVEL',dz.evel,'EVDP',dz.evdp,'MAG',dz.mag,...
       'GCARC',dz.gcarc,'NZYEAR',dz.nzyear,'NZJDAY',dz.nzjday,...
       'NZHOUR',dz.nzhour,'NZMIN',dz.nzmin,'NZSEC',dz.nzsec,'NZMSEC',dz.nzmsec,...
       'NVHDR',dz.nvhdr,'KSTNM',dz.kstnm,'KCMPNM',comt)
% L
   mksac(Ln,L,now,'DELTA',dz.delta,'T0',dz.t0,...
       'STLA',dz.stla,'STLO',dz.stlo,'STEL',dz.stel,'STDP',dz.stdp,...
       'EVLA',dz.evla,'EVLO',dz.evlo,'EVEL',dz.evel,'EVDP',dz.evdp,'MAG',dz.mag,...
       'GCARC',dz.gcarc,'NZYEAR',dz.nzyear,'NZJDAY',dz.nzjday,...
       'NZHOUR',dz.nzhour,'NZMIN',dz.nzmin,'NZSEC',dz.nzsec,'NZMSEC',dz.nzmsec,...
       'NVHDR',dz.nvhdr,'KSTNM',dz.kstnm,'KCMPNM',coml)
% Q
   mksac(Qn,Q,now,'DELTA',dz.delta,'T0',dz.t0,...
       'STLA',dz.stla,'STLO',dz.stlo,'STEL',dz.stel,'STDP',dz.stdp,...
       'EVLA',dz.evla,'EVLO',dz.evlo,'EVEL',dz.evel,'EVDP',dz.evdp,'MAG',dz.mag,...
       'GCARC',dz.gcarc,'NZYEAR',dz.nzyear,'NZJDAY',dz.nzjday,...
       'NZHOUR',dz.nzhour,'NZMIN',dz.nzmin,'NZSEC',dz.nzsec,'NZMSEC',dz.nzmsec,...
       'NVHDR',dz.nvhdr,'KSTNM',dz.kstnm,'KCMPNM',comq)
end